const manifests = [
  // 1–7 Missing
  // 8 at CBL, part of bifolio with 97
  {folio: '8↓', content: 'Rom 5.17–6.4', kenyonPlatesPage: 1, kenyonTextPage: {start: 1, range: 1}, petersonPage: 1, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_8_97/manifest'},
  {folio: '8→', content: 'Rom 6.5–14', kenyonPlatesPage: 1, kenyonTextPage: {start: 1, range: 2}, petersonPage: 2, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_8_97/manifest'},
  // 9–10 Missing
  // 11–12 at CBL
  {folio: '11↓', content: 'Rom 8.15–26', kenyonPlatesPage: 1, kenyonTextPage: {start: 2, range: 2}, petersonPage: 3, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_11/manifest'},
  {folio: '11→', content: 'Rom 8.27–37', kenyonPlatesPage: 1, kenyonTextPage: {start: 3, range: 2}, petersonPage: 4, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_11/manifest'},
  {folio: '12↓', content: 'Rom 8.37–9.9', kenyonPlatesPage: 1, kenyonTextPage: {start: 4, range: 2}, petersonPage: 5, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_12/manifest'},
  {folio: '12→', content: 'Rom 9.9–22', kenyonPlatesPage: 1, kenyonTextPage: {start: 5, range: 2}, petersonPage: 6, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_12/manifest'},
  // 13–15 at CBL, part of bifolia with 92, 91, 90 respectively
  {folio: '13↓', content: 'Rom 9.22–33', kenyonPlatesPage: 1, kenyonTextPage: {start: 6, range: 1}, petersonPage: 7, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_13_92/manifest'},
  {folio: '13→', content: 'Rom 10.1–12', kenyonPlatesPage: 1, kenyonTextPage: {start: 6, range: 2}, petersonPage: 8, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_13_92/manifest'},
  {folio: '14↓', content: 'Rom 10.12–11.3', kenyonPlatesPage: 1, kenyonTextPage: {start: 7, range: 2}, petersonPage: 9, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_14_91/manifest'},
  {folio: '14→', content: 'Rom 11.3–13', kenyonPlatesPage: 1, kenyonTextPage: {start: 8, range: 2}, petersonPage: 10, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_14_91/manifest'},
  {folio: '15↓', content: 'Rom 11.13–24', kenyonPlatesPage: 1, kenyonTextPage: {start: 9, range: 2}, petersonPage: 11, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_15_90/manifest'},
  {folio: '15→', content: 'Rom 11.24–35', kenyonPlatesPage: 1, kenyonTextPage: {start: 10, range: 1}, petersonPage: 12, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_15_90/manifest'},
  // 16–17 at UM
  {folio: '16↓', content: 'Rom 11.35–12.10', kenyonPlatesPage: 1, kenyonTextPage: {start: 10, range: 2}, petersonPage: 13, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3553:6238_30.TIF'},
  {folio: '16→', content: 'Rom 12.10–13.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 11, range: 2}, petersonPage: 14, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3554:6238_31.TIF'},
  {folio: '17↓', content: 'Rom 13.2–12', kenyonPlatesPage: 1, kenyonTextPage: {start: 12, range: 2}, petersonPage: 15, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3555:6238_32.TIF'},
  {folio: '17→', content: 'Rom 13.12–14.8', kenyonPlatesPage: 1, kenyonTextPage: {start: 13, range: 2}, petersonPage: 16, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3556:6238_33.TIF'},
  // Folio 18 below is plated as 'BP 190'
  {folio: '18↓', content: 'Rom 14.9–21', kenyonPlatesPage: 1, kenyonTextPage: {start: 14, range: 2}, petersonPage: 17, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_190/manifest'},
  {folio: '18→', content: 'Rom 14.22–15.10', kenyonPlatesPage: 1, kenyonTextPage: {start: 15, range: 2}, petersonPage: 18, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_190/manifest'},
  // 19–28 at UM
  {folio: '19↓', content: 'Rom 15.11–19', kenyonPlatesPage: 1, kenyonTextPage: {start: 16, range: 2}, petersonPage: 19, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3557:6238_36.TIF'},
  {folio: '19→', content: 'Rom 15.20–29', kenyonPlatesPage: 1, kenyonTextPage: {start: 17, range: 2}, petersonPage: 20, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3558:6238_37.TIF'},
  {folio: '20↓', content: 'Rom 15.29–33; 16.25–27, 1–4', kenyonPlatesPage: 1, kenyonTextPage: {start: 18, range: 2}, petersonPage: 21, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3559:6238_38.TIF'},
  {folio: '20→', content: 'Rom 16.4–14', kenyonPlatesPage: 1, kenyonTextPage: {start: 19, range: 2}, petersonPage: 22, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3560:6238_39.TIF'},
  {folio: '21↓', content: 'Rom 16.14–23', kenyonPlatesPage: 1, kenyonTextPage: {start: 20, range: 2}, petersonPage: 23, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3569:6238_40.TIF'},
  {folio: '21→', content: 'Rom 16.23; Heb 1.1–7', kenyonPlatesPage: 1, kenyonTextPage: {start: 21, range: 2}, petersonPage: 24, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3570:6238_41.TIF'},
  {folio: '22↓', content: 'Heb 1.7–2.3', kenyonPlatesPage: 1, kenyonTextPage: {start: 22, range: 1}, petersonPage: 25, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3561:6238_42.TIF'},
  {folio: '22→', content: 'Heb 2.3–11', kenyonPlatesPage: 1, kenyonTextPage: {start: 23, range: 1}, petersonPage: 26, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3564:6238_43.TIF'},
  {folio: '23↓', content: 'Heb 2.11–3.3', kenyonPlatesPage: 1, kenyonTextPage: {start: 23, range: 2}, petersonPage: 27, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3562:6238_44.TIF'},
  {folio: '23→', content: 'Heb 3.3–13', kenyonPlatesPage: 1, kenyonTextPage: {start: 24, range: 2}, petersonPage: 28, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3565:6238_45.TIF'},
  {folio: '24↓', content: 'Heb 3.13–4.4', kenyonPlatesPage: 1, kenyonTextPage: {start: 25, range: 2}, petersonPage: 29, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3571:6238_46.TIF'},
  {folio: '24→', content: 'Heb 4.4–14', kenyonPlatesPage: 1, kenyonTextPage: {start: 26, range: 2}, petersonPage: 30, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3572:6238_47.TIF'},
  {folio: '25↓', content: 'Heb 4.14–5.8', kenyonPlatesPage: 1, kenyonTextPage: {start: 27, range: 2}, petersonPage: 31, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3573:6238_48.TIF'},
  {folio: '25→', content: 'Heb 5.8–6.4', kenyonPlatesPage: 1, kenyonTextPage: {start: 28, range: 2}, petersonPage: 32, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3574:6238_49.TIF'},
  {folio: '26↓', content: 'Heb 6.4–13', kenyonPlatesPage: 1, kenyonTextPage: {start: 29, range: 2}, petersonPage: 33, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3575:6238_50.TIF'},
  {folio: '26→', content: 'Heb 6.13–7.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 30, range: 1}, petersonPage: 34, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3576:6238_51.TIF'},
  {folio: '27↓', content: 'Heb 7.2–11', kenyonPlatesPage: 1, kenyonTextPage: {start: 31, range: 1}, petersonPage: 35, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3577:6238_52.TIF'},
  {folio: '27→', content: 'Heb 7.11–20', kenyonPlatesPage: 1, kenyonTextPage: {start: 31, range: 2}, petersonPage: 36, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3578:6238_53.TIF'},
  {folio: '28↓', content: 'Heb 7.20–28', kenyonPlatesPage: 1, kenyonTextPage: {start: 32, range: 2}, petersonPage: 37, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3579:6238_54.TIF'},
  {folio: '28→', content: 'Heb 7.28–8.8', kenyonPlatesPage: 1, kenyonTextPage: {start: 33, range: 2}, petersonPage: 38, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3580:6238_55.TIF'},
  // 29 at CBL
  {folio: '29↓', content: 'Heb 8.9–9.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 34, range: 2}, petersonPage: 39, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_29/manifest'},
  {folio: '29→', content: 'Heb 9.2–10', kenyonPlatesPage: 1, kenyonTextPage: {start: 35, range: 2}, petersonPage: 40, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_29/manifest'},
  // 30 at UM
  {folio: '30↓', content: 'Heb 9.10–17', kenyonPlatesPage: 1, kenyonTextPage: {start: 36, range: 2}, petersonPage: 41, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3581:6238_58.TIF'},
  {folio: '30→', content: 'Heb 9.18–26', kenyonPlatesPage: 1, kenyonTextPage: {start: 37, range: 1}, petersonPage: 42, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3582:6238_59.TIF'},
  // 31–39 at CBL
  {folio: '31↓', content: 'Heb 9.26–10.8', kenyonPlatesPage: 1, kenyonTextPage: {start: 38, range: 1}, petersonPage: 43, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_31/manifest'},
  {folio: '31→', content: 'Heb 10.8–22', kenyonPlatesPage: 1, kenyonTextPage: {start: 38, range: 2}, petersonPage: 44, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_31/manifest'},
  {folio: '32↓', content: 'Heb 10.22–32', kenyonPlatesPage: 1, kenyonTextPage: {start: 39, range: 2}, petersonPage: 45, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_32/manifest'},
  {folio: '32→', content: 'Heb 10.32–11.4', kenyonPlatesPage: 1, kenyonTextPage: {start: 40, range: 2}, petersonPage: 46, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_32/manifest'},
  {folio: '33↓', content: 'Heb 11.4–9', kenyonPlatesPage: 1, kenyonTextPage: {start: 41, range: 2}, petersonPage: 47, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_33/manifest'},
  {folio: '33→', content: 'Heb 11.9–17', kenyonPlatesPage: 1, kenyonTextPage: {start: 42, range: 2}, petersonPage: 48, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_33/manifest'},
  {folio: '34↓', content: 'Heb 11.18–26', kenyonPlatesPage: 1, kenyonTextPage: {start: 43, range: 2}, petersonPage: 49, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_34/manifest'},
  {folio: '34→', content: 'Heb 11.26–35', kenyonPlatesPage: 1, kenyonTextPage: {start: 44, range: 2}, petersonPage: 50, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_34/manifest'},
  {folio: '35↓', content: 'Heb 11.35–12.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 45, range: 2}, petersonPage: 51, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_35/manifest'},
  {folio: '35→', content: 'Heb 12.2–11', kenyonPlatesPage: 1, kenyonTextPage: {start: 46, range: 2}, petersonPage: 52, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_35/manifest'},
  {folio: '36↓', content: 'Heb 12.11–21', kenyonPlatesPage: 1, kenyonTextPage: {start: 47, range: 2}, petersonPage: 53, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_36/manifest'},
  {folio: '36→', content: 'Heb 12.21–13.3', kenyonPlatesPage: 1, kenyonTextPage: {start: 48, range: 2}, petersonPage: 54, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_36/manifest'},
  {folio: '37↓', content: 'Heb 13.3–12', kenyonPlatesPage: 1, kenyonTextPage: {start: 49, range: 2}, petersonPage: 55, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_37/manifest'},
  {folio: '37→', content: 'Heb 13.12–20', kenyonPlatesPage: 1, kenyonTextPage: {start: 50, range: 2}, petersonPage: 56, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_37/manifest'},
  {folio: '38↓', content: 'Heb 13.20–1 Cor 1.4', kenyonPlatesPage: 1, kenyonTextPage: {start: 51, range: 2}, petersonPage: 57, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_38/manifest'},
  {folio: '38→', content: '1 Cor 1.4–14', kenyonPlatesPage: 1, kenyonTextPage: {start: 52, range: 2}, petersonPage: 58, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_38/manifest'},
  {folio: '39↓', content: '1 Cor 1.14–23', kenyonPlatesPage: 1, kenyonTextPage: {start: 53, range: 2}, petersonPage: 59, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_39/manifest'},
  {folio: '39→', content: '1 Cor 1.24–2.3', kenyonPlatesPage: 1, kenyonTextPage: {start: 54, range: 2}, petersonPage: 60, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_39/manifest'},
  // 40 at UM
  {folio: '40↓', content: '1 Cor 2.3–11', kenyonPlatesPage: 1, kenyonTextPage: {start: 55, range: 1}, petersonPage: 61, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3583:6238_78.TIF'},
  {folio: '40→', content: '1 Cor 2.11–3.5', kenyonPlatesPage: 1, kenyonTextPage: {start: 55, range: 2}, petersonPage: 62, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3584:6238_79.TIF'},
  // 41–69 at CBL
  {folio: '41↓', content: '1 Cor 3.6–15', kenyonPlatesPage: 1, kenyonTextPage: {start: 56, range: 2}, petersonPage: 63, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_41/manifest'},
  {folio: '41→', content: '1 Cor 3.16–4.4', kenyonPlatesPage: 1, kenyonTextPage: {start: 57, range: 2}, petersonPage: 64, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_41/manifest'},
  {folio: '42↓', content: '1 Cor 4.4–11', kenyonPlatesPage: 1, kenyonTextPage: {start: 58, range: 2}, petersonPage: 65, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_42/manifest'},
  {folio: '42→', content: '1 Cor 4.11–20', kenyonPlatesPage: 1, kenyonTextPage: {start: 59, range: 2}, petersonPage: 66, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_42/manifest'},
  {folio: '43↓', content: '1 Cor 4.20–5.8', kenyonPlatesPage: 1, kenyonTextPage: {start: 60, range: 2}, petersonPage: 67, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_43/manifest'},
  {folio: '43→', content: '1 Cor 5.8–6.4', kenyonPlatesPage: 1, kenyonTextPage: {start: 61, range: 2}, petersonPage: 68, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_43/manifest'},
  {folio: '44↓', content: '1 Cor 6.4–13', kenyonPlatesPage: 1, kenyonTextPage: {start: 62, range: 2}, petersonPage: 69, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_44/manifest'},
  {folio: '44→', content: '1 Cor 6.13–7.3', kenyonPlatesPage: 1, kenyonTextPage: {start: 63, range: 1}, petersonPage: 70, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_44/manifest'},
  {folio: '45↓', content: '1 Cor 7.4–12', kenyonPlatesPage: 1, kenyonTextPage: {start: 63, range: 2}, petersonPage: 71, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_45/manifest'},
  {folio: '45→', content: '1 Cor 7.12–19', kenyonPlatesPage: 1, kenyonTextPage: {start: 64, range: 2}, petersonPage: 72, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_45/manifest'},
  {folio: '46↓', content: '1 Cor 7.20–30', kenyonPlatesPage: 1, kenyonTextPage: {start: 65, range: 2}, petersonPage: 73, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_46/manifest'},
  {folio: '46→', content: '1 Cor 7.30–37', kenyonPlatesPage: 1, kenyonTextPage: {start: 66, range: 2}, petersonPage: 74, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_46/manifest'},
  {folio: '47↓', content: '1 Cor 7.37–8.7', kenyonPlatesPage: 1, kenyonTextPage: {start: 67, range: 2}, petersonPage: 75, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_47/manifest'},
  {folio: '47→', content: '1 Cor 8.7–9.3', kenyonPlatesPage: 1, kenyonTextPage: {start: 68, range: 2}, petersonPage: 76, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_47/manifest'},
  {folio: '48↓', content: '1 Cor 9.4–1', kenyonPlatesPage: 1, kenyonTextPage: {start: 69, range: 2}, petersonPage: 77, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_48/manifest'},
  {folio: '48→', content: '1 Cor 9.12–20', kenyonPlatesPage: 1, kenyonTextPage: {start: 70, range: 2}, petersonPage: 78, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_48/manifest'},
  {folio: '49↓', content: '1 Cor 9.20–10.1', kenyonPlatesPage: 1, kenyonTextPage: {start: 71, range: 2}, petersonPage: 79, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_49/manifest'},
  {folio: '49→', content: '1 Cor 10.1–11', kenyonPlatesPage: 1, kenyonTextPage: {start: 72, range: 2}, petersonPage: 80, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_49/manifest'},
  {folio: '50↓', content: '1 Cor 10.11–20', kenyonPlatesPage: 1, kenyonTextPage: {start: 73, range: 2}, petersonPage: 81, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_50/manifest'},
  {folio: '50→', content: '1 Cor 10.21–31', kenyonPlatesPage: 1, kenyonTextPage: {start: 74, range: 2}, petersonPage: 82, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_50/manifest'},
  {folio: '51↓', content: '1 Cor 10.31–11.7', kenyonPlatesPage: 1, kenyonTextPage: {start: 75, range: 2}, petersonPage: 83, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_51/manifest'},
  {folio: '51→', content: '1 Cor 11.7–18', kenyonPlatesPage: 1, kenyonTextPage: {start: 76, range: 1}, petersonPage: 84, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_51/manifest'},
  {folio: '52↓', content: '1 Cor 11.18–26', kenyonPlatesPage: 1, kenyonTextPage: {start: 76, range: 2}, petersonPage: 85, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_52/manifest'},
  {folio: '52→', content: '1 Cor 11.26–12.3', kenyonPlatesPage: 1, kenyonTextPage: {start: 77, range: 2}, petersonPage: 86, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_52/manifest'},
  {folio: '53→', content: '1 Cor 12.3–13', kenyonPlatesPage: 1, kenyonTextPage: {start: 78, range: 2}, petersonPage: 87, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_53/manifest'},
  {folio: '53↓', content: '1 Cor 12.13–24', kenyonPlatesPage: 1, kenyonTextPage: {start: 79, range: 2}, petersonPage: 88, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_53/manifest'},
  {folio: '54→', content: '1 Cor 12.24–13.1', kenyonPlatesPage: 1, kenyonTextPage: {start: 80, range: 2}, petersonPage: 89, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_54/manifest'},
  {folio: '54↓', content: '1 Cor 13.2–11', kenyonPlatesPage: 1, kenyonTextPage: {start: 81, range: 2}, petersonPage: 90, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_54/manifest'},
  {folio: '55→', content: '1 Cor 13.11–14.6', kenyonPlatesPage: 1, kenyonTextPage: {start: 82, range: 2}, petersonPage: 91, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_55/manifest'},
  {folio: '55↓', content: '1 Cor 14.6–15', kenyonPlatesPage: 1, kenyonTextPage: {start: 83, range: 2}, petersonPage: 92, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_55/manifest'},
  {folio: '56→', content: '1 Cor 14.16–24', kenyonPlatesPage: 1, kenyonTextPage: {start: 84, range: 2}, petersonPage: 93, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_56/manifest'},
  {folio: '56↓', content: '1 Cor 14.24–34', kenyonPlatesPage: 1, kenyonTextPage: {start: 85, range: 2}, petersonPage: 94, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_56/manifest'},
  {folio: '57→', content: '1 Cor 14.34–15.6', kenyonPlatesPage: 1, kenyonTextPage: {start: 86, range: 1}, petersonPage: 95, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_57/manifest'},
  {folio: '57↓', content: '1 Cor 15.6–17', kenyonPlatesPage: 1, kenyonTextPage: {start: 87, range: 1}, petersonPage: 96, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_57/manifest'},
  {folio: '58→', content: '1 Cor 15.17–28', kenyonPlatesPage: 1, kenyonTextPage: {start: 87, range: 2}, petersonPage: 97, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_58/manifest'},
  {folio: '58↓', content: '1 Cor 15.28–39', kenyonPlatesPage: 1, kenyonTextPage: {start: 88, range: 2}, petersonPage: 98, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_58/manifest'},
  {folio: '59→', content: '1 Cor 15.39–51', kenyonPlatesPage: 1, kenyonTextPage: {start: 89, range: 2}, petersonPage: 99, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_59/manifest'},
  {folio: '59↓', content: '1 Cor 15.51–16.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 90, range: 2}, petersonPage: 100, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_59/manifest'},
  {folio: '60→', content: '1 Cor 16.2–1', kenyonPlatesPage: 1, kenyonTextPage: {start: 91, range: 2}, petersonPage: 101, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_60/manifest'},
  {folio: '60↓', content: '1 Cor 16.12–24', kenyonPlatesPage: 1, kenyonTextPage: {start: 92, range: 2}, petersonPage: 102, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_60/manifest'},
  {folio: '61→', content: '2 Cor 1.1–8', kenyonPlatesPage: 1, kenyonTextPage: {start: 93, range: 2}, petersonPage: 103, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_61/manifest'},
  {folio: '61↓', content: '2 Cor 1.8–16', kenyonPlatesPage: 1, kenyonTextPage: {start: 94, range: 2}, petersonPage: 104, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_61/manifest'},
  {folio: '62→', content: '2 Cor 1.16–2.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 95, range: 2}, petersonPage: 105, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_62/manifest'},
  {folio: '62↓', content: '2 Cor 2.3–13', kenyonPlatesPage: 1, kenyonTextPage: {start: 96, range: 2}, petersonPage: 106, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_62/manifest'},
  {folio: '63→', content: '2 Cor 2.13–3.5', kenyonPlatesPage: 1, kenyonTextPage: {start: 97, range: 1}, petersonPage: 107, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_63/manifest'},
  {folio: '63↓', content: '2 Cor 3.5–14', kenyonPlatesPage: 1, kenyonTextPage: {start: 98, range: 1}, petersonPage: 108, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_63/manifest'},
  {folio: '64→', content: '2 Cor 3.14–4.4', kenyonPlatesPage: 1, kenyonTextPage: {start: 98, range: 2}, petersonPage: 109, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_64/manifest'},
  {folio: '64↓', content: '2 Cor 4.4–13', kenyonPlatesPage: 1, kenyonTextPage: {start: 99, range: 2}, petersonPage: 110, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_64/manifest'},
  {folio: '65→', content: '2 Cor 4.13–5.5', kenyonPlatesPage: 1, kenyonTextPage: {start: 100, range: 2}, petersonPage: 111, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_65/manifest'},
  {folio: '65↓', content: '2 Cor 5.5–14', kenyonPlatesPage: 1, kenyonTextPage: {start: 101, range: 2}, petersonPage: 112, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_65/manifest'},
  {folio: '66→', content: '2 Cor 5.14–6.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 102, range: 2}, petersonPage: 113, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_66/manifest'},
  {folio: '66↓', content: '2 Cor 6.3–14', kenyonPlatesPage: 1, kenyonTextPage: {start: 103, range: 2}, petersonPage: 114, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_66/manifest'},
  {folio: '67→', content: '2 Cor 6.14–7.5', kenyonPlatesPage: 1, kenyonTextPage: {start: 104, range: 2}, petersonPage: 115, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_67/manifest'},
  {folio: '67↓', content: '2 Cor 7.5–12', kenyonPlatesPage: 1, kenyonTextPage: {start: 105, range: 2}, petersonPage: 116, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_67/manifest'},
  {folio: '68→', content: '2 Cor 7.12–8.4', kenyonPlatesPage: 1, kenyonTextPage: {start: 106, range: 2}, petersonPage: 117, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_68/manifest'},
  {folio: '68↓', content: '2 Cor 8.4–13', kenyonPlatesPage: 1, kenyonTextPage: {start: 107, range: 1}, petersonPage: 118, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_68/manifest'},
  {folio: '69→', content: '2 Cor 8.13–24', kenyonPlatesPage: 1, kenyonTextPage: {start: 108, range: 1}, petersonPage: 119, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_69/manifest'},
  {folio: '69↓', content: '2 Cor 9.1–7', kenyonPlatesPage: 1, kenyonTextPage: {start: 108, range: 2}, petersonPage: 120, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_69/manifest'},
  // 70–85 at UM
  {folio: '70→', content: '2 Cor 9.7–10.1', kenyonPlatesPage: 1, kenyonTextPage: {start: 109, range: 2}, petersonPage: 121, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3585:6238_136.TIF'},
  {folio: '70↓', content: '2 Cor 10.2–11', kenyonPlatesPage: 1, kenyonTextPage: {start: 110, range: 2}, petersonPage: 122, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3586:6238_137.TIF'},
  {folio: '71→', content: '2 Cor 10.11–11.3', kenyonPlatesPage: 1, kenyonTextPage: {start: 111, range: 2}, petersonPage: 123, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3587:6238_138.TIF'},
  {folio: '71↓', content: '2 Cor 11.3–12', kenyonPlatesPage: 1, kenyonTextPage: {start: 112, range: 2}, petersonPage: 124, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3588:6238_139.TIF'},
  {folio: '72→', content: '2 Cor 11.12–23', kenyonPlatesPage: 1, kenyonTextPage: {start: 113, range: 2}, petersonPage: 125, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3589:6238_140.TIF'},
  {folio: '72↓', content: '2 Cor 11.23–33', kenyonPlatesPage: 1, kenyonTextPage: {start: 114, range: 2}, petersonPage: 126, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3590:6238_141.TIF'},
  {folio: '73→', content: '2 Cor 11.33–12.10', kenyonPlatesPage: 1, kenyonTextPage: {start: 115, range: 2}, petersonPage: 127, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3591:6238_142.TIF'},
  {folio: '73↓', content: '2 Cor 12.10–18', kenyonPlatesPage: 1, kenyonTextPage: {start: 116, range: 2}, petersonPage: 128, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3592:6238_143.TIF'},
  {folio: '74→', content: '2 Cor 12.18–13.5', kenyonPlatesPage: 1, kenyonTextPage: {start: 117, range: 2}, petersonPage: 129, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3593:6238_144.TIF'},
  {folio: '74↓', content: '2 Cor 13.5–13', kenyonPlatesPage: 1, kenyonTextPage: {start: 118, range: 2}, petersonPage: 130, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3594:6238_145.TIF'},
  {folio: '75→', content: 'Eph 1.1–12', kenyonPlatesPage: 1, kenyonTextPage: {start: 119, range: 2}, petersonPage: 131, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3595:6238_146.TIF'},
  {folio: '75↓', content: 'Eph 1.12–21', kenyonPlatesPage: 1, kenyonTextPage: {start: 120, range: 2}, petersonPage: 132, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3599:6238_147.TIF'},
  {folio: '76→', content: 'Eph 1.21–2.10', kenyonPlatesPage: 1, kenyonTextPage: {start: 121, range: 2}, petersonPage: 133, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3600:6238_148.TIF'},
  {folio: '76↓', content: 'Eph 2.10–21', kenyonPlatesPage: 1, kenyonTextPage: {start: 122, range: 2}, petersonPage: 134, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3601:6238_149.TIF'},
  {folio: '77→', content: 'Eph 2.21–3.11', kenyonPlatesPage: 1, kenyonTextPage: {start: 123, range: 1}, petersonPage: 135, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3602:6238_150.TIF'},
  {folio: '77↓', content: 'Eph 3.11–4.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 124, range: 1}, petersonPage: 136, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3603:6238_151.TIF'},
  {folio: '78→', content: 'Eph 4.2–15', kenyonPlatesPage: 1, kenyonTextPage: {start: 124, range: 2}, petersonPage: 137, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3604:6238_152.TIF'},
  {folio: '78↓', content: 'Eph 4.15–26', kenyonPlatesPage: 1, kenyonTextPage: {start: 125, range: 2}, petersonPage: 138, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3606:6238_153.TIF'},
  {folio: '79→', content: 'Eph 4.26–5.8', kenyonPlatesPage: 1, kenyonTextPage: {start: 126, range: 2}, petersonPage: 139, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3607:6238_154.TIF'},
  {folio: '79↓', content: 'Eph 5.8–26', kenyonPlatesPage: 1, kenyonTextPage: {start: 127, range: 2}, petersonPage: 140, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3608:6238_155.TIF'},
  {folio: '80→', content: 'Eph 5.26–6.8', kenyonPlatesPage: 1, kenyonTextPage: {start: 128, range: 2}, petersonPage: 141, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3609:6238_156.TIF'},
  {folio: '80↓', content: 'Eph 6.8–20', kenyonPlatesPage: 1, kenyonTextPage: {start: 129, range: 2}, petersonPage: 142, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3610:6238_157.TIF'},
  {folio: '81→', content: 'Eph 6.20–Gal 1.10', kenyonPlatesPage: 1, kenyonTextPage: {start: 130, range: 2}, petersonPage: 143, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3611:6238_158.TIF'},
  {folio: '81↓', content: 'Gal 1.10–23', kenyonPlatesPage: 1, kenyonTextPage: {start: 131, range: 2}, petersonPage: 144, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3612:6238_159.TIF'},
  {folio: '82→', content: 'Gal 1.23–2.12', kenyonPlatesPage: 1, kenyonTextPage: {start: 132, range: 2}, petersonPage: 145, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3613:6238_160.TIF'},
  {folio: '82↓', content: 'Gal 2.12–3.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 133, range: 2}, petersonPage: 146, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3614:6238_161.TIF'},
  {folio: '83→', content: 'Gal 3.2–16', kenyonPlatesPage: 1, kenyonTextPage: {start: 134, range: 2}, petersonPage: 147, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3615:6238_162.TIF'},
  {folio: '83↓', content: 'Gal 3.16–4.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 135, range: 2}, petersonPage: 148, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3616:6238_163.TIF'},
  {folio: '84→', content: 'Gal 4.2–19', kenyonPlatesPage: 1, kenyonTextPage: {start: 136, range: 2}, petersonPage: 149, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3617:6238_164.TIF'},
  {folio: '84↓', content: 'Gal 4.20–5.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 137, range: 2}, petersonPage: 150, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3618:6238_165.TIF'},
  {folio: '85→', content: 'Gal 5.2–20', kenyonPlatesPage: 1, kenyonTextPage: {start: 138, range: 2}, petersonPage: 151, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3619:6238_166.TIF'},
  {folio: '85↓', content: 'Gal 5.20–6.10', kenyonPlatesPage: 1, kenyonTextPage: {start: 139, range: 2}, petersonPage: 152, canvasIndex: 0, url: 'https://quod.lib.umich.edu/cgi/i/image/api/manifest/apis:3620:6238_167.TIF'},
  // 86–95 at CBL
  {folio: '86→', content: 'Gal 6.10–18; Phil 1.5', kenyonPlatesPage: 1, kenyonTextPage: {start: 140, range: 2}, petersonPage: 153, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_86/manifest'},
  {folio: '86↓', content: 'Phil 1.5–17', kenyonPlatesPage: 1, kenyonTextPage: {start: 141, range: 2}, petersonPage: 154, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_86/manifest'},
  {folio: '87→', content: 'Phil 1.17–29', kenyonPlatesPage: 1, kenyonTextPage: {start: 142, range: 2}, petersonPage: 155, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_87/manifest'},
  {folio: '87↓', content: 'Phil 1.30–2.14', kenyonPlatesPage: 1, kenyonTextPage: {start: 143, range: 2}, petersonPage: 156, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_87/manifest'},
  {folio: '88→', content: 'Phil 2.14–27', kenyonPlatesPage: 1, kenyonTextPage: {start: 144, range: 2}, petersonPage: 157, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_88/manifest'},
  {folio: '88↓', content: 'Phil 2.29–3.10', kenyonPlatesPage: 1, kenyonTextPage: {start: 145, range: 2}, petersonPage: 158, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_88/manifest'},
  {folio: '89→', content: 'Phil 3.10–4.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 146, range: 2}, petersonPage: 159, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_89/manifest'},
  {folio: '89↓', content: 'Phil 4.2–14', kenyonPlatesPage: 1, kenyonTextPage: {start: 147, range: 2}, petersonPage: 160, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_89/manifest'},
  {folio: '90→', content: 'Phil 4.14–Col 1.5', kenyonPlatesPage: 1, kenyonTextPage: {start: 148, range: 2}, petersonPage: 161, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_15_90/manifest'},
  {folio: '90↓', content: 'Col 1.5–15', kenyonPlatesPage: 1, kenyonTextPage: {start: 149, range: 2}, petersonPage: 162, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_15_90/manifest'},

  {folio: '91→', content: 'Col 1.16–27', kenyonPlatesPage: 1, kenyonTextPage: {start: 150, range: 1}, petersonPage: 163, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_14_91/manifest'},
  {folio: '91↓', content: 'Col 1.27–2.8', kenyonPlatesPage: 1, kenyonTextPage: {start: 151, range: 1}, petersonPage: 164, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_14_91/manifest'},
  {folio: '92→', content: 'Col 2.8–22', kenyonPlatesPage: 1, kenyonTextPage: {start: 151, range: 2}, petersonPage: 165, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_13_92/manifest'},
  {folio: '92↓', content: 'Col 2.22–3.13', kenyonPlatesPage: 1, kenyonTextPage: {start: 152, range: 2}, petersonPage: 166, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_13_92/manifest'},
  {folio: '93→', content: 'Col 3.13–4.3', kenyonPlatesPage: 1, kenyonTextPage: {start: 153, range: 2}, petersonPage: 167, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_93/manifest'},
  {folio: '93↓', content: 'Col 4.3–16', kenyonPlatesPage: 1, kenyonTextPage: {start: 154, range: 2}, petersonPage: 168, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_93/manifest'},
  {folio: '94→', content: 'Col 4.16–1 Thess 1.2', kenyonPlatesPage: 1, kenyonTextPage: {start: 155, range: 1}, petersonPage: 169, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_94/manifest'},
  {folio: '94↓', content: '1 Thess 1.8–2.3', kenyonPlatesPage: 1, kenyonTextPage: {start: 155, range: 2}, petersonPage: 170, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_f_94/manifest'},
  // 96 Missing
  // 97 at CBL, part of bifolio with 8
  {folio: '97→', content: '1 Thess 5.5–9', kenyonPlatesPage: 1, kenyonTextPage: {start: 156, range: 1}, petersonPage: 171, canvasIndex: 0, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_8_97/manifest'},
  {folio: '97↓', content: '1 Thess 5.23–28', kenyonPlatesPage: 1, kenyonTextPage: {start: 156, range: 1}, petersonPage: 172, canvasIndex: 1, url: 'https://viewer.cbl.ie/viewer/api/v1/records/BP_II_ff_8_97/manifest'},
];

export default manifests;
